### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by fenomenogr777** [sz3lbi/TWRepetitiveUpcomingAttacks#1]
is it possible instead of that text to show the number next to each attack
ex
if village 500|500 send 5 attacks it will show (5) next to attacks that are coming from 500|500

and also a option rename attacks 
ex
if village500|500 send 5 attacks when u click the option that 5 attacks will rename and add a (5) to the name Ram (5)

**Comment by sz3lbi** [comment]
I will add those features as additional options in script soon. They will be run by separate buttons to keep flexibility of usage.

**Comment by sz3lbi** [comment]
Added.

**Comment by fenomenogr777** [comment]
thanks for the adds

1thing to check 
when u click "add attacks amaount to names" then "change next attack" it needs click to change the name per attack
it would be nice if we could have a auto rename to whole attacks with 1 click especially when u have a lot of attacks it will be very usefull
